services:
  qdrant:
    image: qdrant/qdrant:v1.14.1
    container_name: bejo-qdrant
    ports:
      - "${QDRANT_FIRST_PORT:-6333}:6333"
      - "${QDRANT_SECOND_PORT:-6334}:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - bejo-network

  bejo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bejo-api
    ports:
      - "8000:8000"
    volumes:
      - ./app/uploads:/app/app/uploads
      - ./.env:/app/.env
    environment:
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - bejo-network
    restart: unless-stopped

volumes:
  qdrant_storage:
    driver: local

networks:
  bejo-network:
    driver: bridge
